[package]
name = "aviqtl-rust-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
luna-core = "=3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
semver = "1.0"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
