[workspace]
resolver = "3"
members = [
    "crates/egui-adapter",
    "crates/lab-core",
    "crates/lab-driver",
    "crates/slint-adapter",
]

[workspace.package]
edition = "2024"
rust-version = "1.98"
publish = false

[workspace.dependencies]
aviqtl-gui-lab-core = { path = "crates/lab-core" }
eframe = { version = "0.36.0", default-features = false, features = ["accesskit", "default_fonts", "wgpu"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
slint = { version = "1.17.1", default-features = false, features = ["accessibility", "backend-winit", "compat-1-2", "renderer-femtovg-wgpu", "unstable-wgpu-29"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
debug = 1
