[package]
name = "aviqtl-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aviqtl-media = { path = "../aviqtl-media" }
aviqtl-rust-core = { path = "../aviqtl-core" }
fontdb = { version = "0.23.0", default-features = false, features = ["fs"] }
rustybuzz = "0.20.1"
tiny-skia = { version = "0.12.0", default-features = false, features = ["simd", "std"] }
wgpu = { version = "29.0.1", default-features = false, features = ["std", "wgsl"] }

[lints.rust]
unsafe_code = "forbid"
