[package]
name = "aviqtl-preview"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aviqtl-media = { path = "../aviqtl-media" }
aviqtl-render = { path = "../aviqtl-render" }
aviqtl-rust-core = { path = "../aviqtl-core" }
serde_json = "1.0"
wgpu = { version = "29.0.1", default-features = false, features = ["std", "wgsl"] }

[lints.rust]
unsafe_code = "forbid"
