name: Analysis

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Test Rust + Slint
    uses: ./.github/workflows/rust-checks.yml
  qt:
    name: Test Qt compatibility
    uses: ./.github/workflows/qt-checks.yml
